services:
  - type: web
    name: yt-summary-chatbot
    runtime: python
    plan: free
    region: singapore
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python yt_summary_server.py
